name: Manual Deployment
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag to deploy (e.g. v1.2.3)'
        required: false
        default: ''
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    env:
      IMAGE_NAME: docker.io/lazycomputing/solobit-landing    
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests
        uses: actions/checkout@v4
      - name: Set up Kubeconfig
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}
      - name: Set image tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            IMAGE_TAG="${GITHUB_REF##*/}"
          elif [ -n "${{ github.event.inputs.image_tag }}" ]; then
            IMAGE_TAG="${{ github.event.inputs.image_tag }}"
          else
            IMAGE_TAG="latest"
          fi
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
      - name: Print tag
        run: |
          echo "${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.image_tag }}"
      - name: Deploy to the Kubernetes cluster
        if: ${{ false }}
        uses: azure/k8s-deploy@v4
        with:
          namespace: solobit
          manifests: |
            manifests/deployment.yaml
            manifests/service.yaml
            manifests/ingress.yaml
          images: |
            docker.io/lazycomputing/solobit-landing:${{ steps.set_tag.outputs.tag }}